services:
  api:
    build: .
    hostname: api
    container_name: dotnet_api
    ports:
      - 8080:8080
    deploy:
      restart_policy:
        condition: on-failure
    depends_on: [sqlserver]
    networks:
      - perdidognet
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    env_file: sqlserver.env
    hostname: mssql
    container_name: sqlserver
    ports:
      - 1433:1433
    networks:
      - perdidognet
networks:
  perdidognet:
    driver: bridge
  