// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using perdidog.Data;

#nullable disable

namespace perdidog.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20241220040445_Added lostpet seeder")]
    partial class Addedlostpetseeder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("perdidog.Models.Domain.AnimalType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AnimalTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e1f95dcb-0103-47f6-9ddb-dad7dae65365"),
                            Name = "Cat"
                        },
                        new
                        {
                            Id = new Guid("64d6b2f4-77a3-46d8-91be-fc36ab0103b9"),
                            Name = "Dog"
                        },
                        new
                        {
                            Id = new Guid("b8851d86-8193-48a5-9561-458b82b16f1e"),
                            Name = "Snake"
                        });
                });

            modelBuilder.Entity("perdidog.Models.Domain.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Gender");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Male"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Female"
                        });
                });

            modelBuilder.Entity("perdidog.Models.Domain.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSizeInBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("perdidog.Models.Domain.LostPet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnimalTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AnimalTypeId");

                    b.HasIndex("GenderId");

                    b.ToTable("LostPet");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8b5849f8-554b-4057-bb90-9ba29aba9a1a"),
                            AnimalTypeId = new Guid("64d6b2f4-77a3-46d8-91be-fc36ab0103b9"),
                            GenderId = 1,
                            IsActive = true,
                            Name = "Cabezon",
                            ReportDate = new DateTime(2024, 12, 20, 1, 4, 45, 635, DateTimeKind.Local).AddTicks(8336)
                        },
                        new
                        {
                            Id = new Guid("dfae5930-af55-4aa3-8c11-f141fd75ce69"),
                            AnimalTypeId = new Guid("64d6b2f4-77a3-46d8-91be-fc36ab0103b9"),
                            GenderId = 2,
                            IsActive = true,
                            Name = "Cabezona",
                            ReportDate = new DateTime(2024, 12, 20, 1, 4, 45, 635, DateTimeKind.Local).AddTicks(8399)
                        },
                        new
                        {
                            Id = new Guid("22e71034-37e2-44ad-b31e-928b1f431d45"),
                            AnimalTypeId = new Guid("64d6b2f4-77a3-46d8-91be-fc36ab0103b9"),
                            GenderId = 1,
                            IsActive = true,
                            Name = "Lucky",
                            ReportDate = new DateTime(2024, 12, 20, 1, 4, 45, 635, DateTimeKind.Local).AddTicks(8402)
                        },
                        new
                        {
                            Id = new Guid("8b06fc47-666f-4685-8ec0-d5793b9be883"),
                            AnimalTypeId = new Guid("e1f95dcb-0103-47f6-9ddb-dad7dae65365"),
                            GenderId = 1,
                            IsActive = true,
                            Name = "",
                            ReportDate = new DateTime(2024, 12, 20, 1, 4, 45, 635, DateTimeKind.Local).AddTicks(8405)
                        });
                });

            modelBuilder.Entity("perdidog.Models.Domain.LostPet", b =>
                {
                    b.HasOne("perdidog.Models.Domain.AnimalType", "AnimalType")
                        .WithMany()
                        .HasForeignKey("AnimalTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("perdidog.Models.Domain.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnimalType");

                    b.Navigation("Gender");
                });
#pragma warning restore 612, 618
        }
    }
}
